// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1vRQoYfgZF5VZVGVKJJh8NoEx9hpYLCQ',
    appId: '1:703248185300:web:d666a3d777dd287a6b0841',
    messagingSenderId: '703248185300',
    projectId: 'bubble-2ce01',
    authDomain: 'bubble-2ce01.firebaseapp.com',
    storageBucket: 'bubble-2ce01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGd3VHhq4er2uoNFKnRUBEnwGu9Ui2TV8',
    appId: '1:703248185300:android:d29bb4cd87afbbe16b0841',
    messagingSenderId: '703248185300',
    projectId: 'bubble-2ce01',
    storageBucket: 'bubble-2ce01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-KglYYYDdInNzfcvIHYIM8cpC-9s4_s',
    appId: '1:703248185300:ios:a35812c0ee2ba0256b0841',
    messagingSenderId: '703248185300',
    projectId: 'bubble-2ce01',
    storageBucket: 'bubble-2ce01.firebasestorage.app',
    iosBundleId: 'com.example.rantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-KglYYYDdInNzfcvIHYIM8cpC-9s4_s',
    appId: '1:703248185300:ios:a35812c0ee2ba0256b0841',
    messagingSenderId: '703248185300',
    projectId: 'bubble-2ce01',
    storageBucket: 'bubble-2ce01.firebasestorage.app',
    iosBundleId: 'com.example.rantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1vRQoYfgZF5VZVGVKJJh8NoEx9hpYLCQ',
    appId: '1:703248185300:web:1cec9cfb630a8fab6b0841',
    messagingSenderId: '703248185300',
    projectId: 'bubble-2ce01',
    authDomain: 'bubble-2ce01.firebaseapp.com',
    storageBucket: 'bubble-2ce01.firebasestorage.app',
  );
}
