import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'splash_screen.dart'; // Ensure this matches your splash screen filename

void main() async {
  // Required to initialize Firebase before the app runs
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bubble!',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(fontFamily: 'Inter'), // Assuming you are using a clean font
      home: const SplashScreen(),
    );
  }
}